use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::Result;
use rayon::prelude::*;

use crate::cli::Options;
use crate::model::{ApiItem, Document, DocumentKind, RenderedFile, SourceTree};

const GENERATED_NOTICE: &str = "<!-- This directory is generated by gendoc-md. Do not edit files under this directory manually. -->";

pub fn render_project(
    documents: &[Document],
    tree: &SourceTree,
    options: &Options,
) -> Result<Vec<RenderedFile>> {
    let documents_by_name = documents_by_name(documents);
    let mut files = Vec::with_capacity(documents.len() + 1);
    files.push(render_top_index(
        &documents_by_name,
        tree,
        options.render_toc(),
    ));

    let mut rendered_docs = documents
        .par_iter()
        .map(|document| RenderedFile {
            path: document.output_path.clone(),
            content: render_document(document, &documents_by_name, tree, options.render_toc()),
        })
        .collect::<Vec<_>>();
    rendered_docs.sort_by(|left, right| left.path.cmp(&right.path));
    files.extend(rendered_docs);
    Ok(files)
}

fn documents_by_name(documents: &[Document]) -> BTreeMap<&str, &Document> {
    documents
        .iter()
        .map(|document| (document.import_name.as_str(), document))
        .collect()
}

fn render_top_index(
    documents_by_name: &BTreeMap<&str, &Document>,
    tree: &SourceTree,
    render_toc: bool,
) -> RenderedFile {
    let mut content = String::new();
    content.push_str(GENERATED_NOTICE);
    content.push_str("\n\n# API Documentation\n\n");
    content.push_str(
        "This directory is generated by `gendoc-md`. Do not modify its contents manually.\n\n",
    );
    if render_toc {
        content.push_str("## Table of Contents\n\n");
        content.push_str("- [Top-Level Packages and Modules](#top-level-packages-and-modules)\n\n");
    }

    content.push_str("## Top-Level Packages and Modules\n\n");
    let top_level = tree
        .top_level
        .iter()
        .filter_map(|name| documents_by_name.get(name.as_str()).copied())
        .collect::<Vec<_>>();
    if top_level.is_empty() {
        content.push_str("_No Python packages or modules were found._\n");
    } else {
        for document in top_level {
            content.push_str(&format!(
                "- [{}]({})",
                document.import_name,
                markdown_path(&document.output_path)
            ));
            if let Some(summary) = &document.summary {
                content.push_str(&format!(" - {}", escape_inline(summary)));
            }
            content.push('\n');
        }
    }

    RenderedFile {
        path: PathBuf::from("index.md"),
        content,
    }
}

fn render_document(
    document: &Document,
    documents_by_name: &BTreeMap<&str, &Document>,
    tree: &SourceTree,
    render_toc: bool,
) -> String {
    let mut content = String::new();
    content.push_str(GENERATED_NOTICE);
    content.push_str("\n\n");
    content.push_str(&format!("# {}\n\n", document.import_name));
    if let Some(docstring) = &document.docstring {
        content.push_str(docstring.trim());
        content.push_str("\n\n");
    }

    let children = tree
        .children(&document.import_name)
        .iter()
        .filter_map(|name| documents_by_name.get(name.as_str()).copied())
        .collect::<Vec<_>>();
    let has_children = !children.is_empty();
    let has_exports = !document.exports.is_empty();
    let has_api = !document.apis.is_empty();

    if render_toc {
        content.push_str("## Table of Contents\n\n");
        if has_children {
            content.push_str("- [Packages and Modules](#packages-and-modules)\n");
        }
        if has_exports {
            content.push_str("- [Exports](#exports)\n");
        }
        content.push_str("- [API Documentation](#api-documentation)\n\n");
    }

    if document.kind == DocumentKind::Package {
        content.push_str("## Packages and Modules\n\n");
        if children.is_empty() {
            content.push_str("_No direct child packages or modules._\n\n");
        } else {
            for child in children {
                let link = relative_link(&document.output_path, &child.output_path);
                content.push_str(&format!("- [{}]({})", child.import_name, link));
                if let Some(summary) = &child.summary {
                    content.push_str(&format!(" - {}", escape_inline(summary)));
                }
                content.push('\n');
            }
            content.push('\n');
        }
    }

    if has_exports {
        content.push_str("## Exports\n\n");
        for export in &document.exports {
            content.push_str(&format!("- `{}`\n", export));
        }
        content.push('\n');
    }

    content.push_str("## API Documentation\n\n");
    if has_api {
        for item in &document.apis {
            render_api_item(&mut content, item, 3);
        }
    } else {
        content.push_str("_No public classes or functions defined in this file._\n");
    }

    content
}

fn render_api_item(content: &mut String, item: &ApiItem, level: usize) {
    match item {
        ApiItem::Function(function) => {
            content.push_str(&format!(
                "{} {}\n\n```python\n{}\n```\n",
                "#".repeat(level),
                function.name,
                function.signature
            ));
            if let Some(docstring) = &function.docstring {
                content.push('\n');
                content.push_str(docstring.trim());
                content.push('\n');
            }
            content.push('\n');
        }
        ApiItem::Class(class) => {
            content.push_str(&format!(
                "{} {}\n\n```python\n{}\n```\n",
                "#".repeat(level),
                class.name,
                class.signature
            ));
            if let Some(docstring) = &class.docstring {
                content.push('\n');
                content.push_str(docstring.trim());
                content.push('\n');
            }
            content.push('\n');
            for method in &class.methods {
                content.push_str(&format!(
                    "{} {}.{}\n\n```python\n{}\n```\n",
                    "#".repeat(level + 1),
                    class.name,
                    method.name,
                    method.signature
                ));
                if let Some(docstring) = &method.docstring {
                    content.push('\n');
                    content.push_str(docstring.trim());
                    content.push('\n');
                }
                content.push('\n');
            }
        }
    }
}

fn relative_link(from: &Path, to: &Path) -> String {
    let from_dir = from.parent().unwrap_or_else(|| Path::new(""));
    let from_components = from_dir.components().collect::<Vec<_>>();
    let to_components = to.components().collect::<Vec<_>>();
    let mut shared = 0;
    while shared < from_components.len()
        && shared < to_components.len()
        && from_components[shared] == to_components[shared]
    {
        shared += 1;
    }

    let mut parts = Vec::new();
    for _ in shared..from_components.len() {
        parts.push("..".to_string());
    }
    for component in &to_components[shared..] {
        parts.push(component.as_os_str().to_string_lossy().into_owned());
    }

    if parts.is_empty() {
        ".".to_string()
    } else {
        parts.join("/")
    }
}

fn markdown_path(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn escape_inline(value: &str) -> String {
    value.replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn computes_relative_links() {
        assert_eq!(
            relative_link(Path::new("pkg/index.md"), Path::new("pkg/mod.md")),
            "mod.md"
        );
        assert_eq!(
            relative_link(Path::new("pkg/sub/index.md"), Path::new("pkg/mod.md")),
            "../mod.md"
        );
    }
}
